---

- name: Clean "{{ project_temp_root_dir }}"
  run_once: true
  delegate_to: localhost
  file:
    state: absent
    path: "{{ project_temp_root_dir }}"

- name: checkout "{{git_repo}}" "{{git_branch}}" to "{{ project_temp_root_dir }}"
  run_once: true
  delegate_to: localhost
  local_action: git
  args:
    repo: "{{git_repo}}"
    accept_hostkey: True
    recursive: yes
    remote: origin
    dest: "{{ project_temp_root_dir }}"
    version: "{{git_branch}}"
    update: yes
