---

- name: check if "{{ deploy_project_dir }}" exists
  become: true
  become_user: root
  stat: path="{{ deploy_project_dir }}"
  register: stat_result

- name: create "{{ deploy_project_dir }}"
  when: not stat_result.stat.exists
  become: true
  become_user: root
  file:
    path: "{{ deploy_project_dir }}"
    state: directory

- name: sync from "{{ project_temp_root_dir }}/" to {{ deploy_project_dir }}
  become: true
  become_user: root
  synchronize:
    delete: yes
    rsync_opts:
        - --exclude=.env
    partial: yes
    recursive: yes
    src: "{{ project_temp_root_dir }}/"
    dest: "{{ deploy_project_dir }}"

- name: build
  shell: "{{ item }}"
  become: true
  become_user: root
  with_items:
    - echo "Running service..."
    - docker-compose up --remove-orphans -d --build travel-fe-{{ env }}
  args:
    chdir: "{{ deploy_project_dir }}"